# Generated by Django 5.2.13 on 2026-04-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва організації')),
                ('description', models.TextField(verbose_name='Опис')),
                ('founded_year', models.PositiveIntegerField(verbose_name='Рік заснування')),
                ('volunteer_count', models.PositiveIntegerField(verbose_name='Кількість волонтерів')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва проєкту')),
                ('description', models.TextField(verbose_name='Опис')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization', verbose_name='Організація')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва ресурсу')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='organizations.organization', verbose_name='Організація')),
            ],
        ),
    ]
