# Generated by Django 5.2.13 on 2026-04-28 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва збору')),
                ('description', models.TextField(verbose_name='Опис збору')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цільова сума')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зібрано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_campaigns', to='organizations.organization', verbose_name='Організація')),
            ],
        ),
    ]
